name: test
permissions: {}

on:
  workflow_dispatch:
    inputs:
      developer_build:
        description: "Set to OFF for Release wheels"
        required: false
        default: "ON"

  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize] # Rebuild on new pushes to PR

jobs:
  windows:
    permissions:
      contents: write  # upload
    runs-on: windows-2019
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Update devel release with package
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo aaaaaaaaaaaaa
          touch CMakeLists.txt
          gh release upload v1.0.0 CMakeLists.txt
